--- #YAML:1.0 (see http://module-build.sourceforge.net/META-spec.html)
name: libapreq2
version: 2.03-dev
license: open_source
installdirs: site
distribution_type: module
dynamic_config: 1
provides:
  Apache::Request:
    version: 2.03-dev
  Apache::Cookie:
    version: 2.03-dev
generated_by: build/version_check.pl
requires:
  mod_perl: 1.99_09
  perl: 5.6.1
build_requires:
  Apache::Test: 1.04
  ExtUtils::XSBuilder: 0.23
  mod_perl: 1.99_09
  perl: 5.6.1
