--- #YAML:1.0
name: libapreq2
version: 2.07
license: open_source
installdirs: site
distribution_type: module
dynamic_config: 1
provides:
  Apache2::Request:
    version: 2.07
  Apache2::Cookie:
    version: 2.07
  Apache2::Upload:
    version: 2.07
  APR::Request:
    version: 2.07
  APR::Request::Apache2:
    version: 2.07
  APR::Request::CGI:
    version: 2.07
  APR::Request::Error:
    version: 2.07
  APR::Request::Cookie:
    version: 2.07
  APR::Request::Param:
    version: 2.07
no_index:
  directory:
    - glue/perl/xsbuilder/tables/APR/Request
    - glue/perl/t/response/TestAPI
    - glue/perl/t/response/TestApReq
generated_by: build/version_check.pl
requires:
  mod_perl: 1.999022
  perl: 5.6.1
build_requires:
  Apache::Test: 1.04
  ExtUtils::MakeMaker: 6.15
  ExtUtils::XSBuilder: 0.23
  Test::More: 0.47
  mod_perl: 1.999022
  perl: 5.6.1
