--- #YAML:1.0 (see http://module-build.sourceforge.net/META-spec.html)
name: libapreq2
version: 2.04-dev
license: open_source
installdirs: site
distribution_type: module
dynamic_config: 1
provides:
  Apache::Request:
    version: 2.04-dev
  Apache::Cookie:
    version: 2.04-dev
  Apache::Upload:
    version: 2.04-dev
generated_by: build/version_check.pl
requires:
  mod_perl: 1.9915
  perl: 5.6.1
build_requires:
  Apache::Test: 1.04
  ExtUtils::MakeMaker: 6.15
  ExtUtils::XSBuilder: 0.23
  Test::More: 0.47
  mod_perl: 1.9915
  perl: 5.6.1
