.TH "apreq_status" 3 "19 Jul 2005" "Version 2.06-dev" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apreq_status \- STATUS
2.06-dev released on July 20, 2005
.PP
Contributors looking for a mission:
.PP
.IP "\(bu" 2
just do an egrep on 'TODO' or 'XXX' and see what's there
.PP
.PP
CURRENT RELEASE NOTES:
.PP
RELEASE SHOWSTOPPERS:
.PP
.IP "\(bu" 2
The api docs are currently incorrect.
.IP "\(bu" 2
The perl docs are missing Test::Inline tests.
.PP
.PP
CURRENT VOTES:
.PP
.IP "\(bu" 2
Should we switch to EU::MM for determining the full path to perl? The problem is that some folks move their perl binary post-installation, but never adjust Config.pm. EU::MM is smart, by accepting a full path in $^X or by searching the user's $PATH for $^X, before resorting to Config.pm. However, if we change apreq2, we should also lobby test-dev to adopt the same solution for Apache::Test. Otherwise our test suite will likely fail, even though the rest of the perl build system will presumably still work.
.PP
.PP
+1: joes 0: -1:
.PP
TODO:
.PP
.IP "\(bu" 2
Sadly, the PAUSE indexer still doesn't speak META.yml. We need to find a way to get the APR::Request* packages indexed (with proper version numbers), and prevent the indexer from inspecting the supporting modules in 
.PP

