.TH "apreq_jar_t" 3 "30 Aug 2004" "Version 2.04-dev" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apreq_jar_t \- This is the container class for libapreq cookies.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <apreq_cookie.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBapr_table_t\fP * \fBcookies\fP"
.br
.ti -1c
.RI "void * \fBenv\fP"
.br
.ti -1c
.RI "\fBapr_status_t\fP \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the container class for libapreq cookies. 
.PP
.SH "Field Documentation"
.PP 
.SS "\fBapr_table_t\fP* \fBapreq_jar_t::cookies\fP"
.PP
cookie table 
.SS "void* \fBapreq_jar_t::env\fP"
.PP
environment 
.SS "\fBapr_status_t\fP \fBapreq_jar_t::status\fP"
.PP
status of 'Cookie' header parse 

.SH "Author"
.PP 
Generated automatically by Doxygen for libapreq2 from the source code.
