.TH "Common Gateway Interface" 3 "30 Aug 2004" "Version 2.04-dev" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Common Gateway Interface \- CGI module included in the libapreq2 library.  

.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTRANS\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBAPREQ_MODULE_NAME\fP   'CGI'"
.br
.ti -1c
.RI "#define \fBAPREQ_MODULE_MAGIC_NUMBER\fP   20040731"
.br
.in -1c
.SH "Detailed Description"
.PP 
CGI module included in the libapreq2 library. 
.PP
CGI is the default environment module included in libapreq2... XXX add more info here XXX 
