.TH "Environment Modules" 3 "30 Aug 2004" "Version 2.04-dev" "libapreq2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Environment Modules \- Environments included in libapreq2-2.04-dev.  

.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "group \fBCommon Gateway Interface\fP"
.br
.RI "\fICGI module included in the libapreq2 library. \fP"
.PP
.in +1c

.ti -1c
.RI "group \fBApache 2.X Filter Module\fP"
.br
.RI "\fImod_apreq - DSO that ties libapreq2 to \fBApache\fP 2.X. \fP"
.PP

.in -1c
.SH "Detailed Description"
.PP 
Environments included in libapreq2-2.04-dev. 
.PP
XXX 
